name: Build and test with JitPack

on:
  push:
    tags:
      - v*

jobs:
  build:
    runs_on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Set up JDK 11
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11

      - name: Build with Gradle
        run: ./gradlew build

      - name: JitPack Publish
        uses: actions/setup-java@v2
        with:
          distribution: 'adopt'
          java-version: 11
        run: ./gradlew publishToMavenLocal

      - name: Push to JitPack
        uses: jitpack-io/github-action@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
